<?php

namespace App\Models;

use http\Env\Request;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Country;
use Illuminate\Support\Facades\DB;
use Laravel\Scout\Searchable;


class Brand extends Model
{
    use HasFactory;
    use Searchable;
    protected $guarded = [];

//    public function getRouteKey()
//    {
//        return 'name'; // TODO: Change the autogenerated stub
//    }

    public function country(){

        return $this->belongsTo(Country::class,'country_id');
    }

    public function gallery()
    {
       return $this->belongsTo(Gallery::class);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function discounts()
    {
        return $this->belongsToMany(Discount::class);
    }

}

